app_port: 8081
network:
  cert_name: enutt
  bootstrap_nodes:
    - 127.0.0.1:8081
gossip:
  fanout: 4
  frequency: 200
  # period multiplier
  period_rate: 2
swim:
  initial_rtt: 500
  # period multiplier (initial_rtt * period_rate)
  # has to be at least 3x the initial_rtt
  period_rate: 10
  # Number of peers to pick for indirect pinging
  k: 2
