name: local
config_dir_path: .config/
quic:
  timeout: 30000
  keep_alive: 5000
  cert_domain_name: enutt
client:
  port: 10000
server:
  port: 8000
network:
  bootstrap_nodes:
#    - 127.0.0.1:8096
#    - 127.0.0.1:8097
    - 127.0.0.1:8000
gossip:
  fanout: 2
  frequency: 500
  # period multiplier
  period_rate: 4
swim:
  initial_rtt: 600
  # period multiplier (initial_rtt * period_rate)
  # has to be at least 3x the initial_rtt
  period_rate: 6
  # Number of peers to pick for indirect pinging
  k: 1
